# -*- mode: ruby -*-
# vi: set ft=ruby :

image = "fedora28-ws"

Vagrant.configure("2") do |config|
    config.vm.define "vagrant-#{image}"
    config.vm.box = "#{image}"
    config.vm.box_url = "../../boxes/fedora/vmware/#{image}-0.1.0.box"

    config.vm.provider :vmware_desktop do |v, override|
      v.gui = true
      v.vmx["memsize"] = "1024"
      v.vmx["numvcpus"] = "1"
      v.vmx["cpuid.coresPerSocket"] = "1"
      v.vmx["RemoteDisplay.vnc.enabled"] = "false"
      v.vmx["RemoteDisplay.vnc.port"] = "5900"
      v.vmx["scsi0.virtualDev"] = "lsilogic"
      v.vmx["mks.enable3d"] = "TRUE"
      v.vmx["ethernet0.pcislotnumber"] = "33"
      v.vmx["virtualhw.version"] = "16"
    end
end
