# -*- mode: ruby -*-
# vi: set ft=ruby :

image = "windows10-desktop-vs2017-buildtools"

Vagrant.require_version ">= 1.6.2"

Vagrant.configure("2") do |config|
    config.vm.define "vagrant-#{image}"
    config.vm.box = "#{image}"
    config.vm.box_url = "../../boxes/windows10/vmware/#{image}-0.1.0.box"

    config.vm.communicator = "winrm"

    # Admin user name and password
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"

    config.vm.guest = :windows
    config.windows.halt_timeout = 15

    config.vm.provider :vmware_desktop do |v, override|
        v.gui = true
        v.vmx["memsize"] = "2048"
        v.vmx["numvcpus"] = "2"
        v.vmx["ethernet0.virtualDev"] = "vmxnet3"
        v.vmx["RemoteDisplay.vnc.enabled"] = "false"
        v.vmx["RemoteDisplay.vnc.port"] = "5900"
        v.vmx["scsi0.virtualDev"] = "lsisas1068"
        v.vmx["virtualhw.version"] = "16"
        v.vmx["mks.enable3d"] = "TRUE"
        v.vmx["vhv.enable"] = "TRUE"
        v.vmx["svga.graphicsMemoryKB"] = "1048576"
    end

    config.vm.provision "shell", path: "../scripts/choco.ps1", privileged: true
    config.vm.synced_folder ".", "/vagrant"
end
