# -*- mode: ruby -*-
# vi: set ft=ruby :

image = "debian9-desktop"

Vagrant.configure("2") do |config|
    config.vm.define "vagrant-#{image}"
    config.vm.box = "#{image}"
    config.vm.box_url = "../../boxes/debian/vmware/#{image}-0.1.0.box"

    ["vmware_fusion", "vmware_workstation"].each do |provider|
      config.vm.provider provider do |v, override|
        v.gui = true
        v.vmx["memsize"] = "1024"
        v.vmx["numvcpus"] = "1"
        v.vmx["cpuid.coresPerSocket"] = "1"
        v.vmx["RemoteDisplay.vnc.enabled"] = "false"
        v.vmx["RemoteDisplay.vnc.port"] = "5900"
        v.vmx["scsi0.virtualDev"] = "lsilogic"
        v.vmx["mks.enable3d"] = "TRUE"
      end
    end
end
